name: SageMaker Notebook Workflow

on:
  workflow_dispatch: # Manually triggered workflow
  schedule:
    - cron: "*/2 * * * *"

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH }}
          HOSTNAME: ${{ secrets.IP }}
          USER_NAME: "ec2-user"

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
          echo "Hello World"
